# .github/workflows/check-homepage.yml
name: Demo Online

on:
  schedule:
    - cron: '0 7 * * *'  # Jeden Tag um 07:00 UTC
  workflow_dispatch:      # Manuell auslösbar

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check if website is online
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://demo.maibros.com)
          if [ "$STATUS" -ne 200 ]; then
            echo "Website offline! Status code: $STATUS"
            exit 1
          else
            echo "Website online. Status code: $STATUS"
          fi
